apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  #Base
  - base/main-ingress.yaml

  # Apps
  - apps/hello-world-app/hello-world-app-deployment.yaml
  - apps/hello-world-app/hello-world-app-nodeport.yaml
  - apps/hello-world-app/hello-world-app-pv.yaml

  - apps/http-echo/http-echo-deployment.yaml
  - apps/http-echo/http-echo-nodeport.yaml
