apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/k3dvolume/n8n"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
spec:
  storageClassName: manual
  volumeName: n8n-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
