apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-controller-nginx
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  version: 4.0.6
  targetNamespace: kube-system
  valuesContent: |-
    controller:
      config:
        log-format-upstream: '{"time": "$time_iso8601", "remote_addr": "$remote_addr", "x_forward_for": "$http_x_forwarded_for", "real ip": "$upstream_addr", "request_id": "$req_id",
          "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
          "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer",
          "http_user_agent": "$http_user_agent" }'
        use-proxy-protocol: "false"
        enable-real-ip: "true"
        proxy-real-ip-cidr: "172.18.0.0/24,10.42.0.1"
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
    service:
      externalTrafficPolicy: "Local"
