apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        forwardedHeaders:
          insecure: true
        proxyProtocol:
          insecure: false
      websecure:
        forwardedHeaders:
          insecure: true
        proxyProtocol:
          insecure: false

    tlsOptions:
      default:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384

    logs:
      general:
        level: INFO
      access:
        enabled: true
        format: json
        fields:
          defaultMode: drop
          names:
            StartUTC: keep
            ClientHost: keep
            ClientAddr: keep
            ClientUsername: keep
            RequestMethod: keep
            RequestPath: keep
            RequestProtocol: keep
            RequestHost: keep
            RequestContentSize: keep
            DownstreamStatus: keep
            DownstreamContentSize: keep
            Duration: keep
            OriginDuration: keep
            TraceId: keep
            SpanId: keep
          headers:
            defaultMode: drop
            names:
              X-Forwarded-For: keep
              X-Real-Ip: keep
              Referer: keep
              User-Agent: keep
              X-Request-Id: keep

    metrics:
      prometheus:
        entryPoint: metrics
        service:
          enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
          additionalLabels:
            release: prometheus

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    service:
      spec:
        externalIPs:
          - 84.247.137.55
        externalTrafficPolicy: Local
