apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-storage-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/k3dvolume/affine-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-storage-pvc
spec:
  storageClassName: manual
  volumeName: affine-storage-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/k3dvolume/affine-postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-postgres-pvc
spec:
  storageClassName: manual
  volumeName: affine-postgres-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
