apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: IMMICH_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: IMMICH_DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: IMMICH_DB_DATABASE
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: immich-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: immich-db-data
          persistentVolumeClaim:
            claimName: immich-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
spec:
  selector:
    app: immich-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
