apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/k3dvolume/immich-library"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  storageClassName: manual
  volumeName: immich-library-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/k3dvolume/immich-db"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-pvc
spec:
  storageClassName: manual
  volumeName: immich-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
