apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: immich-server
                port:
                  number: 80
          - pathType: Prefix
            path: "/helloworld"
            backend:
              service:
                name: hello-world-nodeport
                port:
                  number: 80
          - pathType: Prefix
            path: "/pp"
            backend:
              service:
                name: photoprism-server
                port:
                  number: 80
