apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-world-pv
spec:
  storageClassName: manual
  capacity:
    storage: 50m
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/k3dvolume/hello-world"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-pvc
spec:
  storageClassName: manual
  volumeName: hello-world-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50m