apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      app: hello-world-web-server
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-world-web-server
    spec:
      volumes:
        - name: hello-world-volume
          persistentVolumeClaim:
            claimName: hello-world-pvc
      containers:
      - name: hello-world-web-server
        image: ghcr.io/nginx/nginx-unprivileged:stable-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: hello-world-volume
