apiVersion: v1
kind: PersistentVolume
metadata:
  name: wikijs-postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/k3dvolume/wikijs-postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-postgres-pvc
spec:
  storageClassName: manual
  volumeName: wikijs-postgres-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
