apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-pv
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/k3dvolume/photoprism-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-pvc
  labels:
   app: photoprism
spec:
  storageClassName: manual
  volumeName: photoprism-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
      