apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/k3dvolume/paperless-ngx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-pvc
spec:
  storageClassName: manual
  volumeName: paperless-ngx-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
