apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/k3dvolume/paperless/paperless-ngx-postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-postgres-pvc
spec:
  storageClassName: manual
  volumeName: paperless-ngx-postgres-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx-postgres
spec:
  selector:
    matchLabels:
      app: paperless-ngx-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: paperless-ngx-postgres
    spec:
      volumes:
        - name: paperless-ngx-postgres-data
          persistentVolumeClaim:
            claimName: paperless-ngx-postgres-pvc
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: paperless-ngx-postgres-secret
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: paperless-ngx-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx-postgres
spec:
  selector:
    app: paperless-ngx-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
